go:
  # Whenever the Go version is updated here,
  # .github/workflows and Dockerfile should also be updated.
  version: 1.25.0
  cgo: false
repository:
  path: github.com/thelande/sdtd_exporter
build:
  prefix: .
  binaries:
    - name: sdtd_exporter
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -s
    -X github.com/prometheus/common/version.Version={{.Version}}
    -X github.com/prometheus/common/version.Revision={{.Revision}}
    -X github.com/prometheus/common/version.Branch={{.Branch}}
    -X github.com/prometheus/common/version.BuildUser={{user}}@{{host}}
    -X github.com/prometheus/common/version.BuildDate={{date "20060102-15:04:05"}}
tarball:
  prefix: .
  files:
    - LICENSE
    - README.md
crossbuild:
  platforms:
    - linux
    - darwin
    - windows
